(() => {
  const $ = id => document.getElementById(id); let passcode = sessionStorage.getItem('law-quiz-teacher-passcode') || ''; let attempts = []; let selected = null;
  const safe = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char]));
  const nameOf = row => `${row.prefix}${row.first_name} ${row.last_name}`; const dateOf = value => value ? new Date(value).toLocaleString('th-TH', { dateStyle: 'short', timeStyle: 'short' }) : 'ยังไม่ส่ง';
  function toast(message) { const el = $('toast'); el.textContent = message; el.classList.remove('hidden'); setTimeout(() => el.classList.add('hidden'), 4500); }
  function filtered() { const room = $('filter-room').value; const search = $('filter-search').value.trim().toLowerCase(); return attempts.filter(row => (!room || row.room === room) && (!search || `${nameOf(row)} ${row.student_no}`.toLowerCase().includes(search))); }
  function renderStats(rows) { const completed = rows.filter(row => row.completed_at); const average = completed.length ? (completed.reduce((sum, row) => sum + row.score, 0) / completed.length).toFixed(1) : '–'; $('stat-cards').innerHTML = `<div class="stat"><b>${rows.length}</b><span>เริ่มทำทั้งหมด</span></div><div class="stat"><b>${completed.length}</b><span>ส่งคำตอบแล้ว</span></div><div class="stat"><b>${average}</b><span>คะแนนเฉลี่ย / 10</span></div><div class="stat"><b>${new Set(completed.map(row => row.room)).size}</b><span>ห้องที่มีผลส่ง</span></div>`; }
  function renderRows() { const rows = filtered(); renderStats(rows); $('attempt-rows').innerHTML = rows.length ? rows.map(row => `<tr><td><strong>${safe(nameOf(row))}</strong><br><small>เลขที่ ${row.student_no}</small></td><td>${safe(row.room)}</td><td>${row.completed_at ? 'ส่งแล้ว' : '<span class="pending">กำลังทำ</span>'}</td><td>${row.completed_at ? `<span class="score-chip">${row.score} / 10</span>` : '–'}</td><td>${safe(dateOf(row.completed_at))}</td><td><button class="secondary open-detail" data-id="${row.id}">ตรวจคำตอบ</button></td></tr>`).join('') : '<tr><td colspan="6">ไม่พบข้อมูลตามตัวกรอง</td></tr>'; document.querySelectorAll('.open-detail').forEach(button => button.onclick = () => showDetail(attempts.find(row => row.id === button.dataset.id))); }
  function answersMarkup(row, printable = false) { return (row.results || []).map((result, index) => { const picked = result.selectedOption ? `${result.selectedOption}. ${result.options[result.selectedOption.charCodeAt(0) - 65]}` : 'ไม่ได้ตอบ'; const correct = `${result.correctOption}. ${result.options[result.correctOption.charCodeAt(0) - 65]}`; return `<article class="${printable ? 'print-answer' : `result-item ${result.isCorrect ? 'correct' : 'wrong'}`} "><h3>ข้อ ${index + 1}. ${safe(result.question)} ${result.isCorrect ? '✓' : '✕'}</h3><div class="answer-row"><span>นักเรียนตอบ: <b>${safe(picked)}</b></span><span>เฉลย: <b>${safe(correct)}</b></span></div><p class="explanation">${safe(result.explanation)}</p></article>`; }).join(''); }
  function showDetail(row) { if (!row) return; selected = row; const view = $('detail-view'); view.classList.remove('hidden'); view.innerHTML = `<div class="detail-head"><div><h2>${safe(nameOf(row))} <span class="score-chip">${row.score} / 10</span></h2><p>เลขที่ ${row.student_no} · ${safe(row.room)} · ส่ง ${safe(dateOf(row.completed_at))}</p></div><div class="detail-actions"><button id="print-one" class="secondary">PDF รายคน</button></div></div><div class="answer-sheet">${row.completed_at ? answersMarkup(row) : '<p>นักเรียนยังไม่ส่งคำตอบ</p>'}</div><div class="note-panel"><label>บันทึกครู<textarea id="teacher-note" maxlength="2000">${safe(row.teacher_note || '')}</textarea></label><button id="save-note" class="secondary">บันทึกหมายเหตุ</button></div>`; $('print-one').onclick = () => printDetail(row); $('save-note').onclick = () => saveNote(row); view.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
  async function saveNote(row) { try { const response = await fetch(`/api/law-quiz/attempts/${row.id}/note`, { method: 'POST', headers: { 'Content-Type':'application/json', 'x-teacher-passcode': passcode }, body: JSON.stringify({ teacherNote: $('teacher-note').value }) }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.message); attempts = attempts.map(item => item.id === row.id ? payload.attempt : item); selected = payload.attempt; toast('บันทึกหมายเหตุแล้ว'); } catch (error) { toast(error.message || 'บันทึกไม่สำเร็จ'); } }
  function printDetail(row) { document.body.dataset.printMode = 'detail'; $('print-detail-view').innerHTML = `<h1>รายละเอียดคำตอบรายบุคคล</h1><h2>${safe(nameOf(row))} · เลขที่ ${row.student_no} · ${safe(row.room)}</h2><p>คะแนน ${row.score} / 10 · ส่งเมื่อ ${safe(dateOf(row.completed_at))}</p>${answersMarkup(row, true)}${row.teacher_note ? `<p><b>บันทึกครู:</b> ${safe(row.teacher_note)}</p>` : ''}`; window.print(); }
  function printSummary() { const rows = filtered(); document.body.dataset.printMode = 'summary'; $('print-summary-meta').textContent = `ข้อมูล ${rows.length} รายการ · พิมพ์เมื่อ ${dateOf(new Date())}`; $('print-summary-rows').innerHTML = rows.map((row, index) => `<tr><td>${index + 1}</td><td>${safe(nameOf(row))}</td><td>${row.student_no}</td><td>${safe(row.room)}</td><td>${row.completed_at ? `${row.score} / 10` : 'ยังไม่ส่ง'}</td><td>${safe(dateOf(row.completed_at))}</td></tr>`).join(''); window.print(); }
  function printAll() { const rows = filtered().filter(row => row.completed_at); if (!rows.length) return toast('ยังไม่มีคำตอบที่ส่งแล้วในตัวกรองนี้'); document.body.dataset.printMode = 'all'; $('print-all-view').innerHTML = `<h1>คำตอบทั้งหมดตามตัวกรอง</h1>${rows.map(row => `<section class="print-person"><h2>${safe(nameOf(row))} · เลขที่ ${row.student_no} · ${safe(row.room)}</h2><p>คะแนน ${row.score} / 10 · ${safe(dateOf(row.completed_at))}</p>${answersMarkup(row, true)}</section>`).join('')}`; window.print(); }
  async function load() { try { const response = await fetch('/api/law-quiz/attempts', { headers: { 'x-teacher-passcode': passcode } }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.message || 'ไม่สามารถโหลดข้อมูลได้'); attempts = payload.data || []; $('updated-at').textContent = `อัปเดตล่าสุด ${dateOf(new Date())} · ${attempts.length} รายการ`; renderRows(); if (selected) showDetail(attempts.find(row => row.id === selected.id)); } catch (error) { toast(error.message); } }
  $('login-form').onsubmit = async event => { event.preventDefault(); passcode = $('passcode').value; const response = await fetch('/api/verify-passcode', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({passcode}) }); const payload = await response.json(); if (!payload.success) return toast('รหัสผ่านครูไม่ถูกต้อง'); sessionStorage.setItem('law-quiz-teacher-passcode', passcode); $('login-view').classList.add('hidden'); $('dashboard-view').classList.remove('hidden'); load(); };
  Array.from({ length: 15 }, (_, i) => $('filter-room').insertAdjacentHTML('beforeend', `<option value="ม.3/${i + 1}">ม.3/${i + 1}</option>`)); $('filter-room').onchange = renderRows; $('filter-search').oninput = renderRows; $('refresh').onclick = load; $('print-summary').onclick = printSummary; $('print-all').onclick = printAll; window.onafterprint = () => { delete document.body.dataset.printMode; };
  if (passcode) { $('passcode').value = passcode; $('login-form').requestSubmit(); }
})();
